version: "3.5"
services:
  nginx:
    image: nginx:1.14.0
    deploy:
      replicas: 1
    logging:
      driver: fluentd
      options:
        tag: "perspectives_nginx.{{.ID}}"
        fluentd-async-connect: "true"
    networks:
      - net

  database:
    image: perspectives-postgresql
    volumes:
      - postgresql:/var/lib/postgresql/data
    deploy:
      replicas: 1
    logging:
      driver: fluentd
      options:
        tag: "perspectives_database.{{.ID}}"
        fluentd-async-connect: "true"
    networks:
      - net

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.0
    volumes:
      - projections_elasticsearch:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    deploy:
      replicas: 1
    configs:
      - source: elasticsearch
        target: /usr/share/elasticsearch/config/elasticsearch.yml
    networks:
      - net

  webapp:
    image: perspectives-webapp:${WEBAPP_VERSION:-latest}
    depends_on:
      - database
    deploy:
      replicas: 2
    logging:
      driver: fluentd
      options:
        tag: "perspectives_webapp.{{.ID}}"
        fluentd-async-connect: "true"
    environment:
      ALGOLIA_PLACES_APIKEY_FILE: /run/secrets/algolia_places_apikey
      ALGOLIA_PLACES_APPID_FILE: /run/secrets/algolia_places_appid
      OAUTH2_CLIENT_ID_FILE: /run/secrets/oauth2_client_id
      OAUTH2_CLIENT_SECRET_FILE: /run/secrets/oauth2_client_secret
      MAILJET_APIKEY_PUBLIC_FILE: /run/secrets/mailjet_apikey_public
      MAILJET_APIKEY_PRIVATE_FILE: /run/secrets/mailjet_apikey_private
      AUTOLOGIN_SECRET_KEY_FILE: /run/secrets/autologin_secret_key
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
      PLAY_HTTP_SECRET_KEY_FILE: /run/secrets/play_http_secret_key
      GOOGLE_TAG_MANAGER_CONTAINER_ID_FILE: /run/secrets/google_tag_manager_container_id
      SLACK_WEBHOOK_URL_FILE: /run/secrets/slack_webhook_url
    secrets:
      - algolia_places_apikey
      - algolia_places_appid
      - oauth2_client_id
      - oauth2_client_secret
      - mailjet_apikey_public
      - mailjet_apikey_private
      - autologin_secret_key
      - postgres_password
      - play_http_secret_key
      - google_tag_manager_container_id
      - slack_webhook_url
    networks:
      - net

  batchs:
    image: perspectives-batchs:${BATCHS_VERSION:-latest}
    depends_on:
      - database
    deploy:
      replicas: 1
    logging:
      driver: fluentd
      options:
        tag: "perspectives_batchs.{{.ID}}"
        fluentd-async-connect: "true"
    environment:
      MAILJET_APIKEY_PUBLIC_FILE: /run/secrets/mailjet_apikey_public
      MAILJET_APIKEY_PRIVATE_FILE: /run/secrets/mailjet_apikey_private
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
      PLAY_HTTP_SECRET_KEY_FILE: /run/secrets/play_http_secret_key
      AUTOLOGIN_SECRET_KEY_FILE: /run/secrets/autologin_secret_key
    secrets:
      - mailjet_apikey_public
      - mailjet_apikey_private
      - postgres_password
      - play_http_secret_key
      - autologin_secret_key
    networks:
      - net

  backups:
    image: perspectives-backups
    volumes:
      - postgresql_backups:/var/opt/backups/postgresql
    deploy:
      replicas: 1
    logging:
      driver: fluentd
      options:
        tag: "perspectives_backups.{{.ID}}"
        fluentd-async-connect: "true"
    networks:
      - net

  fluentbit:
    image: fluent/fluent-bit:0.13
    deploy:
      replicas: 1
    configs:
      - source: fluent_bit
        target: /fluent-bit/etc/fluent-bit.conf
    ports:
      - "24224:24224"
    networks:
      - net

networks:
  net:

volumes:
  postgresql:
  postgresql_backups:
  export_poleemploi:
  projections_elasticsearch:

configs:
  nginx:
    file: ./nginx/nginx.conf
  elasticsearch:
    file: ./elasticsearch/elasticsearch.yml
  fluent_bit:
    file: ./fluent-bit/fluent-bit.conf

secrets:
  algolia_places_apikey:
    external: true
  algolia_places_appid:
    external: true
  oauth2_client_id:
    external: true
  oauth2_client_secret:
    external: true
  mailjet_apikey_public:
    external: true
  mailjet_apikey_private:
    external: true
  autologin_secret_key:
    external: true
  postgres_password:
    external: true
  play_http_secret_key:
    external: true
  google_tag_manager_container_id:
    external: true
  slack_webhook_url:
    external: true
