version: "3.5"
services:
  nginx:
    image: nginx:1.14.0
    ports:
      - "8080:80"
    deploy:
      replicas: 1
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - net

  database:
    image: perspectives-postgres
    volumes:
      - postgresql:/var/lib/postgresql/data
    env_file:
      - dev.env
    deploy:
      replicas: 1
    networks:
      - net

  webapp:
    image: webapp
    depends_on:
      - database
      - nginx
    env_file:
      - dev.env
    deploy:
      replicas: 1
    ports:
      - "9000:9000"
    networks:
      - net

networks:
  net:

volumes:
  postgresql:
