version: "3.5"
services:
  nginx:
    image: nginx:1.14.0
    deploy:
      replicas: 1
    logging:
      driver: fluentd
      options:
        tag: "perspectives_nginx.{{.ID}}"
        fluentd-async-connect: "true"
    networks:
      - net

  database:
    image: perspectives-postgresql
    volumes:
      - postgresql:/var/lib/postgresql/data
    deploy:
      replicas: 1
    logging:
      driver: fluentd
      options:
        tag: "perspectives_database.{{.ID}}"
        fluentd-async-connect: "true"
    networks:
      - net

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.0
    volumes:
      - projections_elasticsearch:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    deploy:
      replicas: 1
    configs:
      - source: elasticsearch
        target: /usr/share/elasticsearch/config/elasticsearch.yml
    networks:
      - net

  webapp:
    image: perspectives-webapp
    depends_on:
      - database
    deploy:
      replicas: 2
    logging:
      driver: fluentd
      options:
        tag: "perspectives_webapp.{{.ID}}"
        fluentd-async-connect: "true"
    networks:
      - net

  batchs:
    image: perspectives-batchs
    depends_on:
      - database
    deploy:
      replicas: 1
    logging:
      driver: fluentd
      options:
        tag: "perspectives_batchs.{{.ID}}"
        fluentd-async-connect: "true"
    networks:
      - net

  backups:
    image: perspectives-backups
    volumes:
      - postgresql_backups:/var/opt/backups/postgresql
    deploy:
      replicas: 1
    logging:
      driver: fluentd
      options:
        tag: "perspectives_backups.{{.ID}}"
        fluentd-async-connect: "true"
    networks:
      - net

  fluentbit:
    image: fluent/fluent-bit:0.13
    deploy:
      replicas: 1
    configs:
      - source: fluent_bit
        target: /fluent-bit/etc/fluent-bit.conf
    ports:
      - "24224:24224"
    networks:
      - net

networks:
  net:

volumes:
  postgresql:
  postgresql_backups:
  export_poleemploi:
  projections_elasticsearch:

configs:
  nginx:
    file: ./nginx/nginx.conf
  elasticsearch:
    file: ./elasticsearch/elasticsearch.yml
  fluent_bit:
    file: ./fluent-bit/fluent-bit.conf
