version: "3.5"
services:
  nginx:
    ports:
      - "8080:80"
    configs:
      - source: nginx
        target: /etc/nginx/nginx.conf

  database:
    env_file:
      - dev.env

  webapp:
    env_file:
      - dev.env

  batchs:
    env_file:
      - dev.env
    volumes:
      - export_poleemploi:/var/perspectives/export_poleemploi

  fluentbit:
    env_file:
      - dev.env
