version: "3.5"
services:
  nginx:
    image: perspectives-nginx-https
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
    deploy:
      replicas: 1
    logging:
      driver: fluentd
      options:
        tag: "perspectives_nginx.{{.ID}}"
        fluentd-async-connect: "true"
    networks:
      - net

  database:
    image: perspectives-postgresql
    volumes:
      - postgresql:/var/lib/postgresql/data
    env_file:
      - prod.env
    deploy:
      replicas: 1
    logging:
      driver: fluentd
      options:
        tag: "perspectives_database.{{.ID}}"
        fluentd-async-connect: "true"
    networks:
      - net

  database_cron_backup:
    image: perspectives-postgresql-cron-backup
    depends_on:
      - database
    volumes:
      - postgresql_backups:/var/opt/postgresql-cron-backup
    deploy:
      replicas: 1
    logging:
      driver: fluentd
      options:
        tag: "perspectives_database.{{.ID}}"
        fluentd-async-connect: "true"
    networks:
      - net

  elasticsearch:
    image: perspectives-elasticsearch
    volumes:
      - projections_elasticsearch:/usr/share/elasticsearch/data
    env_file:
      - prod.env
    ports:
      - "9200:9200"
    deploy:
      replicas: 1
    networks:
      - net

  webapp:
    image: perspectives-webapp
    depends_on:
      - database
    env_file:
      - prod.env
    deploy:
      replicas: 2
    logging:
      driver: fluentd
      options:
        tag: "perspectives_webapp.{{.ID}}"
        fluentd-async-connect: "true"
    ports:
      - "9000:9000"
    networks:
      - net

  batchs:
    image: perspectives-batchs
    depends_on:
      - database
    env_file:
      - prod.env
    volumes:
      - type: bind
        source: /mnt/datalakepe/depuis_datalake
        target: /var/perspectives/export_poleemploi
    deploy:
      replicas: 1
    logging:
      driver: fluentd
      options:
        tag: "perspectives_batchs.{{.ID}}"
        fluentd-async-connect: "true"
    ports:
      - "9001:9000"
    networks:
      - net

  fluentbit:
    image: perspectives-fluent-bit
    extra_hosts:
      - "perspectives.elastic.pole-emploi.fr:137.74.30.34"
    env_file:
      - prod.env
    deploy:
      replicas: 1
    ports:
      - "24224:24224"
    networks:
      - net

networks:
  net:

volumes:
  postgresql:
  postgresql_backups:
  export_poleemploi:
  projections_elasticsearch:
