version: "3"
services:
  nginx:
    image: nginx
    ports:
      - "8080:80"
    deploy:
          replicas: 1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - net
  webapp:
    image: webapp
    deploy:
      replicas: 1
    ports:
      - "9000:9000"
    networks:
      - net

networks:
  net: