version: "3.5"
services:
  nginx:
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
    configs:
      - source: nginx
        target: /etc/nginx/nginx.conf
    logging:
      driver: json-file

  database:
    env_file:
      - recette.env
    logging:
      driver: json-file

  webapp:
    env_file:
      - recette.env
    deploy:
      replicas: 1
    logging:
      driver: json-file

  batchs:
    env_file:
      - recette.env
    logging:
      driver: json-file
    volumes:
      - export_poleemploi:/var/perspectives/export_poleemploi

  backups:
    logging:
      driver: json-file

  fluentbit:
    env_file:
      - recette.env