version: "3.5"
services:
  nginx:
    image: perspectives-nginx
    ports:
      - "8080:80"
    deploy:
      replicas: 1
    networks:
      - net

  database:
    image: perspectives-postgresql
    volumes:
      - postgresql:/var/lib/postgresql/data
    env_file:
      - dev.env
    deploy:
      replicas: 1
    networks:
      - net

  database_cron_backup:
    image: perspectives-postgresql-cron-backup
    volumes:
      - postgresql_backups:/var/opt/postgresql-cron-backup
    env_file:
      - dev.env
    deploy:
      replicas: 1
    networks:
      - net

  webapp:
    image: perspectives-webapp
    depends_on:
      - database
      - nginx
    env_file:
      - dev.env
    volumes:
      - export_poleemploi:/var/perspectives/export_poleemploi
    deploy:
      replicas: 1
    ports:
      - "9000:9000"
    networks:
      - net

networks:
  net:

volumes:
  postgresql:
  postgresql_backups:
  export_poleemploi:
