version: "3.5"
services:
  nginx:
    image: perspectives-nginx
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
    deploy:
      replicas: 1
    logging:
      driver: fluentd
      options:
        tag: "perspectives_nginx.{{.ID}}"
        fluentd-async-connect: "true"
    networks:
      - net

  database:
    image: perspectives-postgresql
    volumes:
      - postgresql:/var/lib/postgresql/data
    env_file:
      - recette.env
    deploy:
      replicas: 1
    logging:
      driver: fluentd
      options:
        tag: "perspectives_database.{{.ID}}"
        fluentd-async-connect: "true"
    networks:
      - net

  database_cron_backup:
    image: perspectives-postgresql-cron-backup
    depends_on:
      - database
    volumes:
      - postgresql_backups:/var/opt/postgresql-cron-backup
    deploy:
      replicas: 1
    logging:
      driver: fluentd
      options:
        tag: "perspectives_database.{{.ID}}"
        fluentd-async-connect: "true"
    networks:
      - net

  elasticsearch:
    image: perspectives-elasticsearch
    volumes:
      - projections_elasticsearch:/usr/share/elasticsearch/data
    env_file:
      - recette.env
    ports:
      - "9200:9200"
    deploy:
      replicas: 1
    networks:
      - net

  webapp:
    image: perspectives-webapp
    depends_on:
      - database
    env_file:
      - recette.env
    deploy:
      replicas: 2
    logging:
      driver: fluentd
      options:
        tag: "perspectives_webapp.{{.ID}}"
        fluentd-async-connect: "true"
    networks:
      - net

  batchs:
    image: perspectives-batchs
    depends_on:
      - database
    env_file:
      - recette.env
    volumes:
      - export_poleemploi:/var/perspectives/export_poleemploi
    deploy:
      replicas: 1
    logging:
      driver: fluentd
      options:
        tag: "perspectives_batchs.{{.ID}}"
        fluentd-async-connect: "true"
    networks:
      - net

  fluentbit:
    image: perspectives-fluent-bit
    env_file:
      - recette.env
    deploy:
      replicas: 1
    ports:
      - "24224:24224"
    networks:
      - net

networks:
  net:

volumes:
  postgresql:
  postgresql_backups:
  export_poleemploi:
  projections_elasticsearch:
