version: "3.5"
services:
  nginx:
    image: perspectives-nginx
    ports:
      - "8080:80"
    deploy:
      replicas: 1
    logging:
      driver: fluentd
      options:
        tag: "perspectives_nginx.{{.ID}}"
        fluentd-async-connect: "true"
    networks:
      - net

  database:
    image: perspectives-postgresql
    volumes:
      - postgresql:/var/lib/postgresql/data
    env_file:
      - dev.env
    deploy:
      replicas: 1
    logging:
      driver: fluentd
      options:
        tag: "perspectives_database.{{.ID}}"
        fluentd-async-connect: "true"
    networks:
      - net

  elasticsearch:
    image: perspectives-elasticsearch
    volumes:
      - projections_elasticsearch:/usr/share/elasticsearch/data
    env_file:
      - dev.env
    ports:
      - "9200:9200"
    deploy:
      replicas: 1
    networks:
      - net

  webapp:
    image: perspectives-webapp
    depends_on:
      - database
    env_file:
      - dev.env
    deploy:
      replicas: 2
    logging:
      driver: fluentd
      options:
        tag: "perspectives_webapp.{{.ID}}"
        fluentd-async-connect: "true"
    networks:
      - net

  batchs:
    image: perspectives-batchs
    depends_on:
      - database
    env_file:
      - dev.env
    volumes:
      - export_poleemploi:/var/perspectives/export_poleemploi
    deploy:
      replicas: 1
    logging:
      driver: fluentd
      options:
        tag: "perspectives_batchs.{{.ID}}"
        fluentd-async-connect: "true"
    networks:
      - net

  backups:
    image: perspectives-backups
    volumes:
      - postgresql_backups:/var/opt/backups/postgresql
    deploy:
      replicas: 1
    logging:
      driver: fluentd
      options:
        tag: "perspectives_backups.{{.ID}}"
        fluentd-async-connect: "true"
    networks:
      - net

  fluentbit:
    image: perspectives-fluent-bit
    env_file:
      - dev.env
    deploy:
      replicas: 1
    ports:
      - "24224:24224"
    networks:
      - net

networks:
  net:

volumes:
  postgresql:
  postgresql_backups:
  export_poleemploi:
  projections_elasticsearch:
