version: "3.5"
services:
  nginx:
    image: perspectives-nginx-https
    ports:
      - "80:80"
      - "443:443"
    deploy:
      replicas: 1
    networks:
      - net

  database:
    image: perspectives-postgresql
    volumes:
      - postgresql:/var/lib/postgresql/data
    env_file:
      - prod.env
    deploy:
      replicas: 1
    networks:
      - net

  database_cron_backup:
    image: perspectives-postgresql-cron-backup
    depends_on:
      - database
    volumes:
      - postgresql_backups:/var/opt/postgresql-cron-backup
    deploy:
      replicas: 1
    networks:
      - net

  elasticsearch:
    image: perspectives-elasticsearch
    depends_on:
      - database
    env_file:
      - prod.env
    ports:
      - "9200:9200"
    deploy:
      replicas: 1
    networks:
      - net

  webapp:
    image: perspectives-webapp
    depends_on:
      - database
      - nginx
    env_file:
      - prod.env
    deploy:
      replicas: 2
    networks:
      - net

  batchs:
    image: perspectives-batchs
    depends_on:
      - database
    env_file:
      - prod.env
    volumes:
      - export_poleemploi:/var/perspectives/export_poleemploi
    deploy:
      replicas: 1
    networks:
      - net

networks:
  net:

volumes:
  postgresql:
  postgresql_backups:
  export_poleemploi:
